
export const PAGE_ACTIONS = {
    CHANGE_CURRENT_PAGE: 'CHANGE_CURRENT_PAGE'
}

export const LOGIN_ACTIONS = {
    LOGIN: 'LOGIN',
    LOGOUT: 'LOGOUT'
}

export const PLAYER_SETUP = {
    NUM_PLAYERS: 'NUM_PLAYERS',
    CHANGE_PLAYER_ATTRIBUTE: 'CHANGE_PLAYER_ATTRIBUTE',
}